Repository codesquad-member-2020/todo-7, pull requests merged in 2020-04, with the labels that each got.

#18 [BE] Spring boot와 MySQL 연결을 위한 초기 설정
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/todo7/BE/BeApplication.java
  BE/src/main/java/todo7/BE/config/DatabaseConfig.java
  BE/src/main/java/todo7/BE/config/PropertyConfig.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/ddl.sql
  BE/src/main/resources/dml.sql
  BE/src/main/resources/logback.xml
  BE/src/test/java/todo7/BE/BeApplicationTests.java
Labels: BE

#25 [FE] todo화면에 대한 CSS
  FE/src/style/common/lib/reset.css
  FE/src/style/style.css
Labels: FE

#26 [FE] Webpack 빌드 환경 설정
  FE/.gitignore
  FE/package-lock.json
  FE/package.json
  FE/webpack.config.js
Labels: FE

#22 [BE] root aggregate project fetch api 구현
  BE/src/main/java/todo7/BE/controller/ProjectController.java
  BE/src/main/java/todo7/BE/domain/Card.java
  BE/src/main/java/todo7/BE/domain/Category.java
  BE/src/main/java/todo7/BE/domain/Project.java
  BE/src/main/java/todo7/BE/domain/ProjectRepository.java
  BE/src/main/resources/ddl.sql
  BE/src/main/resources/dml.sql
Labels: BE

#28 [FE] Webpack 빌드 환경 추가 설정
  FE/.babelrc
  FE/package-lock.json
  FE/package.json
  FE/src/javascript/main.js
  FE/src/page/index.html
  FE/src/style/todo.css
  FE/webpack.config.js
Labels: FE

#30 [FE] 메뉴 액티비티 열고 닫는 기능 구현
  FE/.vscode/settings.json
  FE/src/javascript/menuComponent.js
  FE/src/page/index.html
  FE/src/style/style.css
Labels: FE

#31 [FE] fetch요청 함수 추가
  FE/src/javascript/util/fetchRequest.js
Labels: FE

#35 [FE] column 카드 추가, 취소 버튼 이벤트 등록
  FE/src/javascript/columnComponent.js
  FE/src/javascript/main.js
  FE/src/page/index.html
  FE/src/style/style.css
Labels: FE

#33 [BE] 백엔드 설정 수정
  BE/src/main/java/todo7/BE/config/CorsConfig.java
  BE/src/main/java/todo7/BE/config/DatabaseConfig.java
  BE/src/main/java/todo7/BE/config/DevWebConfig.java
  BE/src/main/java/todo7/BE/config/PropertyConfig.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/logback.xml
Labels: BE

#39 [FE] 초기 fetch 데이터 렌더링 기능 구현
  FE/src/javascript/columnComponent.js
  FE/src/javascript/component/card.js
  FE/src/javascript/component/cardForm.js
  FE/src/javascript/component/column.js
  FE/src/javascript/component/menu.js
  FE/src/javascript/main.js
  FE/src/javascript/menuComponent.js
  FE/src/page/index.html
Labels: FE

#40 [FE] column별 총 카드 수 렌더 기능
  FE/src/javascript/component/card.js
  FE/src/javascript/component/column.js
  FE/src/javascript/main.js
Labels: FE

#41 [FE] 카드 추가 기능
  FE/src/javascript/component/card.js
  FE/src/javascript/component/cardForm.js
  FE/src/javascript/component/column.js
  FE/src/javascript/util/util.js
  FE/src/style/style.css
Labels: FE

#43 [FE] 카드 삭제 기능
  FE/src/javascript/component/card.js
Labels: FE

#42 [BE] CRUD card entity API 기능 구현
  BE/src/main/java/todo7/BE/config/DevWebConfig.java
  BE/src/main/java/todo7/BE/domain/Card.java
  BE/src/main/java/todo7/BE/domain/Category.java
  BE/src/main/java/todo7/BE/domain/Project.java
  BE/src/main/java/todo7/BE/web/CardController.java
  BE/src/main/java/todo7/BE/web/ProjectController.java
  BE/src/main/java/todo7/BE/web/exception/NotFoundException.java
  BE/src/main/resources/ddl.sql
  BE/src/main/resources/dml.sql
Labels: BE

#48 [FE] 카드 수정 기능
  FE/src/javascript/component/card.js
  FE/src/javascript/component/column.js
  FE/src/javascript/component/menu.js
  FE/src/javascript/component/modal.js
  FE/src/javascript/main.js
  FE/src/page/index.html
  FE/src/style/style.css
Labels: FE, FE-Review

#34 [be-review] 백엔드 환경설정
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/todo7/BE/BeApplication.java
  BE/src/main/java/todo7/BE/config/DatabaseConfig.java
  BE/src/main/java/todo7/BE/config/DevWebConfig.java
  BE/src/main/java/todo7/BE/controller/ProjectController.java
  BE/src/main/java/todo7/BE/domain/Card.java
  BE/src/main/java/todo7/BE/domain/Category.java
  BE/src/main/java/todo7/BE/domain/Project.java
  BE/src/main/java/todo7/BE/domain/ProjectRepository.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/ddl.sql
  BE/src/main/resources/dml.sql
  BE/src/main/resources/logback.xml
  BE/src/test/java/todo7/BE/BeApplicationTests.java
Labels: be-review

#49 [FE] 카드 추가, 수정, 삭제 서버와 연결
  FE/src/javascript/component/card.js
  FE/src/javascript/component/cardForm.js
  FE/src/javascript/component/column.js
  FE/src/javascript/component/modal.js
  FE/src/javascript/constants/serviceUrls.js
  FE/src/javascript/main.js
  FE/src/javascript/util/util.js
  FE/src/page/index.html
  FE/src/style/style.css
Labels: FE

#44 [BE] JWT 토큰, 인터셉터 기능 구현
  BE/build.gradle
  BE/src/main/java/todo7/BE/config/CommonWebConfig.java
  BE/src/main/java/todo7/BE/utils/AuthCheckInterceptor.java
  BE/src/main/java/todo7/BE/utils/JwtUtils.java
Labels: BE

#55 [FE] 드래그앤드랍 기능 구현
  FE/src/javascript/component/card.js
  FE/src/javascript/component/column.js
  FE/src/javascript/dragAndDrop.js
  FE/src/javascript/main.js
  FE/src/javascript/util/util.js
  FE/src/style/style.css
Labels: FE

#56 [BE] card 이동 API 기능 구현
  BE/src/main/java/todo7/BE/config/DevWebConfig.java
  BE/src/main/java/todo7/BE/domain/Card.java
  BE/src/main/java/todo7/BE/domain/Category.java
  BE/src/main/java/todo7/BE/domain/Project.java
  BE/src/main/java/todo7/BE/web/CardController.java
  BE/src/main/java/todo7/BE/web/CategoryController.java
  BE/src/main/java/todo7/BE/web/MoveCardCommand.java
Labels: BE

#57 셀 삭제 기능구현, 네트워크 통신
  iOS/.gitignore
  iOS/ToDo/ToDo.xcodeproj/project.pbxproj
  iOS/ToDo/ToDo.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/ToDo/ToDo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/ToDo/ToDo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/ToDo/ToDo.xcodeproj/project.xcworkspace/xcuserdata/yun.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/ToDo/ToDo.xcodeproj/xcuserdata/yun.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/ToDo/ToDo/AppDelegate.swift
  iOS/ToDo/ToDo/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/ToDo/ToDo/Assets.xcassets/Contents.json
  iOS/ToDo/ToDo/Base.lproj/LaunchScreen.storyboard
  iOS/ToDo/ToDo/Base.lproj/Main.storyboard
  iOS/ToDo/ToDo/ContainerViewController/ContainerTableSectionHeaderView.swift
  iOS/ToDo/ToDo/ContainerViewController/ContainerTableViewCell.swift
  iOS/ToDo/ToDo/ContainerViewController/ContainerTableViewController.swift
  iOS/ToDo/ToDo/ContainerViewController/ContainerTableViewDataSource.swift
  iOS/ToDo/ToDo/Info.plist
  iOS/ToDo/ToDo/Network/Model/Model.swift
  iOS/ToDo/ToDo/Network/Provider.swift
  iOS/ToDo/ToDo/Network/Service.swift
  iOS/ToDo/ToDo/NewCard/NewCardTextViewDelegate.swift
  iOS/ToDo/ToDo/NewCard/NewCardViewController.swift
  iOS/ToDo/ToDo/Notification/Name.swift
  iOS/ToDo/ToDo/SceneDelegate.swift
  iOS/ToDo/ToDo/ViewController.swift
  iOS/ToDo/ToDoTests/Info.plist
  iOS/ToDo/ToDoTests/ToDoTests.swift
Labels: iOS 리뷰 요청

#58 [FE] 카드 이동 기능 Fix & Refactoring
  FE/src/javascript/component/card.js
  FE/src/javascript/component/cardForm.js
  FE/src/javascript/component/column.js
  FE/src/javascript/dragAndDrop.js
  FE/src/javascript/main.js
  FE/src/style/style.css
Labels: FE

#62 카드 추가 기능 구현
  iOS/ToDo/ToDo.xcodeproj/project.pbxproj
  iOS/ToDo/ToDo.xcodeproj/project.xcworkspace/xcuserdata/yun.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/ToDo/ToDo/Base.lproj/Main.storyboard
  iOS/ToDo/ToDo/ContainerViewController/ContainerTableSectionHeaderView.swift
  iOS/ToDo/ToDo/ContainerViewController/ContainerTableViewController.swift
  iOS/ToDo/ToDo/ContainerViewController/ContainerTableViewDataSource.swift
  iOS/ToDo/ToDo/Network/Model/Model.swift
  iOS/ToDo/ToDo/Network/Provider.swift
  iOS/ToDo/ToDo/Network/Service.swift
  iOS/ToDo/ToDo/NewCard/NewCardTextViewDelegate.swift
  iOS/ToDo/ToDo/NewCard/NewCardTitleTextViewDelegate.swift
  iOS/ToDo/ToDo/NewCard/NewCardViewController.swift
  iOS/ToDo/ToDo/Notification/Name.swift
  iOS/ToDo/ToDo/ViewController.swift
Labels: iOS, iOS 리뷰 요청
